"""Write frontend/lib/normalize.fixtures.json from the Python reference
normalizer, so the TypeScript grader is tested against the same cases."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests"))

from app.course.normalize import answers_match  # noqa: E402
from test_course import CASES, FIXTURES  # noqa: E402

MATCH = [
    ("γυνη", ["γυνή"], False),
    ("γυνη", ["γυνή"], True),
    ("ἐστιν", ["ἐστί(ν)"], False),
    ("ἐστι", ["ἐστί(ν)"], False),
    ("ὁ Λύσις παῖς ἐστιν.", ["ὁ Λύσις παῖς ἐστιν"], True),
    ("ὀ", ["ὁ"], False),
    ("", ["ὁ"], False),
    ("καλὸς", ["καλός"], True),
    ("ΚΕΡΑΜΕΥΣ", ["κεραμεύς"], False),
    ("τω οικω", ["τῷ οἴκῳ"], False),
    ("τω οικω", ["τῷ οἴκῳ"], True),
]


def main() -> None:
    doc = {
        "_about": "Generated by backend/scripts/export_normalize_fixtures.py; do not edit by hand.",
        "normalize": [{"text": t, "accents": a, "want": w} for t, a, w in CASES],
        "match": [{"given": g, "accepted": acc, "accents": a, "want": answers_match(g, acc, a)} for g, acc, a in MATCH],
    }
    FIXTURES.write_text(json.dumps(doc, ensure_ascii=False, indent=1) + "\n", "utf-8")
    print(f"wrote {FIXTURES}")


if __name__ == "__main__":
    main()
