"""The grammar section: model paradigms with explanations and examples.

Each paradigm names a model word, the class the engine should decline it as,
a short explanation for a learner and two example sentences. Tables are
generated by `nominal.decline` (and, for verbs, `verb.conjugate`) at request
time, so they stay consistent with the vocabulary pages.
"""

from __future__ import annotations

from functools import lru_cache

from .nominal import decline

SECTIONS = [
    ("article", "The article", "ὁ ἡ τό marks gender, number and case; learn it first, because nouns and adjectives follow its endings."),
    ("nouns-1", "First declension", "Feminine nouns in -η and -ᾱ (and a few masculines in -ης, -ᾱς). Genitive plural always -ῶν."),
    ("nouns-2", "Second declension", "Masculine (and some feminine) nouns in -ος, neuters in -ον."),
    ("nouns-3", "Third declension", "Consonant and vowel stems: find the stem from the genitive, then add -ος, -ι, -α; -ες, -ων, -σι, -ας."),
    ("adjectives", "Adjectives", "Adjectives agree with their noun in gender, number and case; the endings are those of the article and the nouns."),
    ("pronouns", "Pronouns & numerals", "Personal, demonstrative, relative, interrogative/indefinite and reflexive pronouns, and the declinable numerals."),
    ("verbs", "Verbs", "Person, number, tense, mood and voice. Learn the principal parts and the endings; the engine builds every form from them."),
]


def P(id, section, title, lemma, kind, subclass, morph, explanation, examples):
    return {
        "id": id, "section": section, "title": title, "lemma": lemma, "kind": kind, "subclass": subclass,
        "morph": morph, "explanation": explanation, "examples": [{"greek": g, "english": e} for g, e in examples],
    }


def N(id, title, lemma, genitive, gender, subclass, explanation, examples, section=None):
    section = section or {"noun-1": "nouns-1", "noun-2": "nouns-2"}.get(subclass, "nouns-3")
    return P(id, section, title, lemma, "noun", subclass, {"genitive": genitive, "gender": gender}, explanation, examples)


def V(id, title, lemma, explanation, examples):
    """A verb paradigm: the forms come from the lexicon entry of `lemma`."""
    return P(id, "verbs", title, lemma, "verb", "verb", {}, explanation, examples)


def A(id, title, lemma, subclass, feminine, neuter, explanation, examples, terminations=3, kind="adjective", section="adjectives"):
    morph = {"terminations": terminations, "feminine": feminine, "neuter": neuter}
    if kind == "pronoun":
        morph = {"forms": [lemma, feminine, neuter]}
    return P(id, section, title, lemma, kind, subclass, morph, explanation, examples)


PARADIGMS: list[dict] = [
    P("article", "article", "ὁ, ἡ, τό — the", "ὁ", "article", "article", {},
      "The article has no vocative. Its endings (-ου, -ῷ, -όν; -οί, -ῶν, -οῖς, -ούς and the feminine -ῆς, -ῇ, -ήν; -αί, -ῶν, -αῖς, -άς) reappear in every -ος/-η adjective.",
      [("ὁ ἀνὴρ ἐν τῷ ἀγρῷ πονεῖ.", "The man is working in the field."),
       ("αἱ γυναῖκες πρὸς τὴν κρήνην βαδίζουσιν.", "The women are walking to the spring.")]),

    N("timi", "τιμή — nouns in -η", "τιμή", "τιμῆς", "f", "noun-1",
      "The commonest first-declension type: -η throughout the singular. τιμή is oxytone, so the genitive and dative take a circumflex.",
      [("ἡ ἀρετὴ τιμῆς ἀξία ἐστίν.", "Virtue is worthy of honour."), ("τὰς τιμὰς τῶν θεῶν φυλάττομεν.", "We keep the honours of the gods.")]),
    N("chora", "χώρα — nouns in long -ᾱ", "χώρα", "χώρας", "f", "noun-1",
      "After ε, ι or ρ the singular keeps ᾱ instead of η (χώρας, χώρᾳ, χώραν). The plural is the same for every first-declension noun.",
      [("ἡ χώρα καλή ἐστιν.", "The land is beautiful."), ("οἱ πολέμιοι εἰς τὴν χώραν εἰσβάλλουσιν.", "The enemy are invading the country.")]),
    N("thalatta", "θάλαττα — nouns in short -α", "θάλαττα", "θαλάττης", "f", "noun-1",
      "Short α in the nominative and accusative, but -ης, -ῃ in the genitive and dative (the stem does not end in ε, ι, ρ). The accent moves to the penult when the ending is long.",
      [("ὁ ναύτης τὴν θάλατταν φιλεῖ.", "The sailor loves the sea."), ("ἐν τῇ θαλάττῃ πολλαὶ νῆσοί εἰσιν.", "There are many islands in the sea.")]),
    N("aletheia", "ἀλήθεια — short -α after ε, ι, ρ", "ἀλήθεια", "ἀληθείας", "f", "noun-1",
      "Short α in the nominative (so the accent can sit on the antepenult), but -ᾱς, -ᾳ in the genitive and dative because the stem ends in ι.",
      [("τὴν ἀλήθειαν λέγε.", "Tell the truth."), ("ἡ ἀλήθεια τῆς δόξης κρείττων ἐστίν.", "Truth is stronger than opinion.")]),
    N("polites", "πολίτης — masculines in -ης", "πολίτης", "πολίτου", "m", "noun-1",
      "Masculine first-declension nouns take -ς in the nominative and -ου in the genitive (borrowed from the second declension). Nouns in -της have the vocative in -α: πολῖτα.",
      [("οἱ πολῖται ἐν τῇ ἐκκλησίᾳ βουλεύονται.", "The citizens deliberate in the assembly."), ("ὦ πολῖτα, ἄκουε τοῦ ῥήτορος.", "Citizen, listen to the speaker.")]),
    N("neanias", "νεανίας — masculines in -ᾱς", "νεανίας", "νεανίου", "m", "noun-1",
      "Like πολίτης but with ᾱ: νεανίας, νεανίου, νεανίᾳ, νεανίαν, vocative νεανία.",
      [("ὁ νεανίας τρέχει πρὸς τὸ ἄστυ.", "The young man runs to town."), ("οἱ τῶν νεανιῶν πατέρες ἀποροῦσιν.", "The young men's fathers are at a loss.")]),

    N("logos", "λόγος — masculines in -ος", "λόγος", "λόγου", "m", "noun-2",
      "The model second-declension noun. Note the vocative in -ε and the accusative plural in -ους.",
      [("ὁ λόγος ἀληθής ἐστιν.", "The account is true."), ("τοῖς λόγοις τοῦ Σωκράτους πειθόμεθα.", "We are persuaded by Socrates' words.")]),
    N("doron", "δῶρον — neuters in -ον", "δῶρον", "δώρου", "n", "noun-2",
      "Neuters have the same form for nominative, accusative and vocative; the plural of those cases ends in -α. A neuter plural subject takes a singular verb.",
      [("τὰ δῶρα τοῖς θεοῖς φέρομεν.", "We bring the gifts to the gods."), ("τὸ δῶρον καλόν ἐστιν.", "The gift is beautiful.")]),
    N("hodos", "ὁδός — feminines in -ος", "ὁδός", "ὁδοῦ", "f", "noun-2",
      "A few second-declension nouns are feminine (ὁδός, νῆσος, νόσος): same endings, feminine article and adjective.",
      [("ἡ ὁδὸς μακρά ἐστιν.", "The road is long."), ("κατὰ τὴν ὁδὸν βαδίζομεν.", "We walk along the road.")]),
    N("nous", "νοῦς — contracted -οος", "νοῦς", "νοῦ", "m", "noun-2",
      "νόος contracts to νοῦς in Attic: ο+ο → ου, ο+ῳ → ῳ, ο+οι → οι, ο+α → α (with a circumflex wherever the contraction produced one).",
      [("νοῦν ἔχε.", "Have sense."), ("ὁ νοῦς τοῦ ἀνθρώπου θεῖός ἐστιν.", "The mind of man is divine.")]),

    N("phylax", "φύλαξ — velar stems", "φύλαξ", "φύλακος", "m", "noun-3-cons",
      "Stem φυλακ-: κ + ς gives ξ in the nominative singular and dative plural. Genitive -ος, dative -ι, accusative -α.",
      [("οἱ φύλακες τὰς πύλας φυλάττουσιν.", "The guards are guarding the gates."), ("τῷ φύλακι τὸ ἀργύριον δίδωσιν.", "He gives the money to the guard.")]),
    N("soma", "σῶμα — neuters in -μα", "σῶμα", "σώματος", "n", "noun-3-cons",
      "Stem σωματ-: the τ is lost at the end of the word (σῶμα) and before σ (σώμασι). Nominative = accusative; plural in -ατα.",
      [("τὸ σῶμα καὶ ἡ ψυχή.", "Body and soul."), ("τοῖς σώμασι πονοῦμεν, ταῖς ψυχαῖς μανθάνομεν.", "We toil with our bodies and learn with our souls.")]),
    N("elpis", "ἐλπίς — dental stems", "ἐλπίς", "ἐλπίδος", "f", "noun-3-cons",
      "Stem ἐλπιδ-: the δ drops before ς (ἐλπίς, ἐλπίσι). The vocative is the bare stem without δ: ἐλπί.",
      [("ἐλπίδα ἔχομεν σωτηρίας.", "We have hope of safety."), ("αἱ ἐλπίδες τῶν ἀνθρώπων πολλάκις ψευδεῖς εἰσιν.", "People's hopes are often false.")]),
    N("daimon", "δαίμων — nasal stems", "δαίμων", "δαίμονος", "m/f", "noun-3-cons",
      "Stem δαιμον-: the nominative lengthens ο to ω and has no ς; ν drops before σ (δαίμοσι). The vocative is the stem with recessive accent: δαῖμον.",
      [("ὁ δαίμων τὸν ἄνθρωπον σῴζει.", "The god saves the man."), ("τοῖς δαίμοσι θύομεν.", "We sacrifice to the gods.")]),
    N("geron", "γέρων — -ντ stems", "γέρων", "γέροντος", "m", "noun-3-cons",
      "Stem γεροντ-: -ντ drops before σ and the vowel lengthens (γέρουσι). Vocative γέρον.",
      [("οἱ γέροντες ἐν τῇ ἀγορᾷ κάθηνται.", "The old men sit in the market-place."), ("τῷ γέροντι βοηθοῦμεν.", "We help the old man.")]),
    N("pater", "πατήρ — ρ stems with vowel gradation", "πατήρ", "πατρός", "m", "noun-3-irregular",
      "πατήρ, μήτηρ, θυγάτηρ (and ἀνήρ) alternate long, short and zero grades of the stem: πατήρ, πατέρα, πατρός. Dative plural πατράσι.",
      [("ὁ πατὴρ τὸν παῖδα φιλεῖ.", "The father loves his child."), ("τῷ πατρὶ πείθου.", "Obey your father.")]),
    N("aner", "ἀνήρ — man", "ἀνήρ", "ἀνδρός", "m", "noun-3-irregular",
      "Like πατήρ, but a δ is inserted between ν and ρ: ἀνδρός, ἀνδρί, ἄνδρα. The vocative ἄνερ has a recessive accent.",
      [("οἱ ἄνδρες πρὸς τὸν πόλεμον ἐξέρχονται.", "The men go out to war."), ("ὦ ἄνερ, τί λέγεις;", "Sir, what are you saying?")]),
    N("gyne", "γυνή — woman", "γυνή", "γυναικός", "f", "noun-3-irregular",
      "Stem γυναικ-, with the accent on the ending in the genitive and dative (as with monosyllabic stems). Vocative γύναι.",
      [("ἡ γυνὴ τὸν ἄνδρα καλεῖ.", "The woman calls her husband."), ("αἱ γυναῖκες οἴκοι μένουσιν.", "The women stay at home.")]),
    N("genos", "γένος — σ-stem neuters", "γένος", "γένους", "n", "noun-3-sigma",
      "Stem γενεσ-: the σ drops between vowels and the vowels contract: γένε(σ)ος → γένους, γένε(σ)ι → γένει, γένε(σ)α → γένη, γενέ(σ)ων → γενῶν.",
      [("τὸ γένος τῶν Ἑλλήνων παλαιόν ἐστιν.", "The race of the Greeks is ancient."), ("πάντα τὰ γένη τῶν ζῴων.", "All the kinds of animals.")]),
    N("polis", "πόλις — ι-stems", "πόλις", "πόλεως", "f", "noun-3-iota",
      "Stem πολι-/πολε-: genitive -εως (accent stays on the antepenult), accusative -ιν, plural -εις for both nominative and accusative.",
      [("ἡ πόλις τοὺς πολίτας σῴζει.", "The city protects its citizens."), ("ἐν ταῖς πόλεσι νόμοι εἰσίν.", "In cities there are laws.")]),
    N("basileus", "βασιλεύς — -εύς nouns", "βασιλεύς", "βασιλέως", "m", "noun-3-eus",
      "Stem βασιλευ-/βασιλε-: genitive -έως, accusative -έᾱ, nominative plural -ῆς (older) or -εῖς, vocative -εῦ.",
      [("ὁ βασιλεὺς τῶν Περσῶν μέγας ἐστίν.", "The king of the Persians is great."), ("τῷ βασιλεῖ πάντες πείθονται.", "Everyone obeys the king.")]),
    N("naus", "ναῦς — ship", "ναῦς", "νεώς", "f", "noun-3-irregular",
      "A much-contracted stem ναυ-/νη-/νε-: learn it as a set. Dative plural ναυσί.",
      [("αἱ νῆες εἰς τὸν λιμένα πλέουσιν.", "The ships sail into the harbour."), ("ἐν τῇ νηὶ πολλοὶ ναῦταί εἰσιν.", "There are many sailors in the ship.")]),
    N("pous", "πούς — monosyllabic stems", "πούς", "ποδός", "m", "noun-3-cons",
      "Nouns whose stem is one syllable (πούς, χείρ, νύξ, πῦρ) accent the ending in the genitive and dative: ποδός, ποδί, ποδῶν, ποσί.",
      [("τῷ ποδὶ τὸν λίθον κινεῖ.", "He moves the stone with his foot."), ("οἱ πόδες τοῦ ἵππου ταχεῖς εἰσιν.", "The horse's feet are swift.")]),

    A("agathos", "ἀγαθός, -ή, -όν — three endings", "ἀγαθός", "adj-1-2", "ἀγαθή", "ἀγαθόν",
      "Masculine like λόγος, feminine like τιμή, neuter like δῶρον. Oxytone adjectives take the circumflex in the genitive and dative of all genders.",
      [("ὁ ἀγαθὸς ἀνὴρ τοὺς φίλους ὠφελεῖ.", "The good man helps his friends."), ("ἀγαθῆς γυναικὸς ἔργον.", "The work of a good woman.")]),
    A("dikaios", "δίκαιος, -ᾱ, -ον — feminine in -ᾱ", "δίκαιος", "adj-1-2", "δικαία", "δίκαιον",
      "After ε, ι, ρ the feminine has ᾱ (δικαία, δικαίας). The feminine genitive plural keeps the adjective's own accent (δικαίων), unlike nouns.",
      [("δίκαιός ἐστιν ὁ ἀνήρ.", "The man is just."), ("ἡ δικαία πόλις εὐδαίμων ἐστίν.", "The just city is happy.")]),
    A("adynatos", "ἀδύνατος, -ον — two endings", "ἀδύνατος", "adj-1-2", None, "ἀδύνατον",
      "Compound adjectives (ἀ-δύνατος, σύμ-μαχος, ἄ-δικος) have no separate feminine: the -ος forms serve for masculine and feminine.",
      [("ἀδύνατόν ἐστι τοῦτο ποιεῖν.", "It is impossible to do this."), ("ἡ ὁδὸς ἀδύνατος ἦν τοῖς ἵπποις.", "The road was impassable for the horses.")], terminations=2),
    A("alethes", "ἀληθής, -ές — σ-stem adjectives", "ἀληθής", "adj-3-es", None, "ἀληθές",
      "Third-declension adjectives of two endings; like γένος, the σ drops and vowels contract: ἀληθοῦς, ἀληθεῖ, ἀληθῆ, ἀληθεῖς.",
      [("ὁ λόγος ἀληθής ἐστιν.", "The story is true."), ("τὰ ἀληθῆ λέγε.", "Tell the truth.")], terminations=2),
    A("tachys", "ταχύς, -εῖα, -ύ", "ταχύς", "adj-us", "ταχεῖα", "ταχύ",
      "Masculine and neuter are third declension (stem ταχυ-/ταχε-), the feminine is first declension in -εῖα.",
      [("ὁ ἵππος ταχύς ἐστιν.", "The horse is fast."), ("ταχεῖα ἡ ναῦς.", "The ship is fast.")]),
    A("beltion", "βελτίων, -ον — comparatives in -ων", "βελτίων", "adj-3-on", None, "βέλτιον",
      "Stem βελτιον-; beside the full forms Attic prefers the contracted βελτίω (acc. sg., neut. pl.) and βελτίους (nom./acc. pl.).",
      [("ὁ σοφὸς βελτίων ἐστὶ τοῦ ἄφρονος.", "The wise man is better than the fool."), ("βέλτιόν ἐστι σιγᾶν.", "It is better to keep silent.")], terminations=2),
    A("pas", "πᾶς, πᾶσα, πᾶν — all, every", "πᾶς", "adj-pas", "πᾶσα", "πᾶν",
      "Stem παντ-/πασ-. Without the article: ‘every’; with it: ‘the whole’ or ‘all the’.",
      [("πάντες οἱ ἄνθρωποι θνητοί εἰσιν.", "All human beings are mortal."), ("πᾶσα ἡ πόλις χαίρει.", "The whole city rejoices.")]),
    A("polys", "πολύς, πολλή, πολύ — much, many", "πολύς", "adj-irregular", "πολλή", "πολύ",
      "Only πολύς, πολύν, πολύ come from the short stem; everything else is regular πολλ-.",
      [("πολλοὶ ἄνθρωποι ἐν τῇ ἀγορᾷ εἰσιν.", "There are many people in the market-place."), ("πολὺν χρόνον ἐμένομεν.", "We waited a long time.")]),
    A("megas", "μέγας, μεγάλη, μέγα — great", "μέγας", "adj-irregular", "μεγάλη", "μέγα",
      "Like πολύς: μέγας, μέγαν, μέγα from the short stem, the rest from μεγαλ-.",
      [("μέγας ἐστὶν ὁ ποταμός.", "The river is big."), ("μεγάλην πόλιν οἰκοῦμεν.", "We live in a great city.")]),
    A("chalkous", "χαλκοῦς, -ῆ, -οῦν — contracted adjectives", "χαλκοῦς", "adj-1-2", "χαλκῆ", "χαλκοῦν",
      "χάλκεος contracts (ε+ο → ου, ε+α → η after a consonant), and every ending carries a circumflex.",
      [("χαλκοῦν ἄγαλμα ἐν τῷ ἱερῷ ἐστιν.", "There is a bronze statue in the temple."), ("χαλκοῖς ὅπλοις μάχονται.", "They fight with bronze weapons.")]),

    A("ego", "ἐγώ, σύ — personal pronouns", "ἐγώ", "pronoun", None, None,
      "The first- and second-person pronouns. The unaccented forms μου, μοι, με, σου, σοι, σε are enclitic and unemphatic; ἐμοῦ, ἐμοί, ἐμέ are emphatic or follow prepositions.",
      [("ἐγὼ μὲν λέγω, σὺ δὲ ἀκούεις.", "I speak and you listen."), ("δός μοι τὸ βιβλίον.", "Give me the book.")], kind="pronoun", section="pronouns"),
    A("sy", "σύ — you", "σύ", "pronoun", None, None,
      "Second person singular and plural (ὑμεῖς).",
      [("σὺ τίς εἶ;", "Who are you?"), ("ὑμῖν λέγω.", "I am telling you (pl.).")], kind="pronoun", section="pronouns"),
    A("autos", "αὐτός, -ή, -ό — self; him, her, it", "αὐτός", "pronoun", "αὐτή", "αὐτό",
      "Three uses: emphatic ‘-self’ (αὐτὸς ὁ βασιλεύς), ‘the same’ with the article (ὁ αὐτὸς ἀνήρ), and in the oblique cases the plain pronoun ‘him, her, it, them’.",
      [("αὐτὸς ὁ βασιλεὺς ἦλθεν.", "The king himself came."), ("ὁρῶ αὐτόν.", "I see him.")], kind="pronoun", section="pronouns"),
    A("houtos", "οὗτος, αὕτη, τοῦτο — this", "οὗτος", "pronoun", "αὕτη", "τοῦτο",
      "Rough breathing where the article has it, τ- elsewhere; the diphthong is αυ before endings in η/α, ου before ο/ω. Used with the article: οὗτος ὁ ἀνήρ.",
      [("οὗτος ὁ ἀνὴρ σοφός ἐστιν.", "This man is wise."), ("ταῦτα λέγω.", "This is what I say.")], kind="pronoun", section="pronouns"),
    A("hode", "ὅδε, ἥδε, τόδε — this (here)", "ὅδε", "pronoun", "ἥδε", "τόδε",
      "The article with the suffix -δε; points to what follows or what is near the speaker.",
      [("τάδε λέγει ὁ ἄγγελος.", "The messenger says the following."), ("ἥδε ἡ ὁδὸς εἰς ἄστυ φέρει.", "This road leads to town.")], kind="pronoun", section="pronouns"),
    A("ekeinos", "ἐκεῖνος, -η, -ο — that", "ἐκεῖνος", "pronoun", "ἐκείνη", "ἐκεῖνο",
      "Declined like αὐτός; points to what is remote.",
      [("ἐκεῖνος ὁ οἶκος μέγας ἐστίν.", "That house is big."), ("ἐν ἐκείνῳ τῷ χρόνῳ.", "At that time.")], kind="pronoun", section="pronouns"),
    A("hos", "ὅς, ἥ, ὅ — who, which", "ὅς", "pronoun", "ἥ", "ὅ",
      "The relative pronoun agrees with its antecedent in gender and number; its case comes from its own clause.",
      [("ὁ ἀνὴρ ὃν ὁρᾷς σοφός ἐστιν.", "The man whom you see is wise."), ("ἡ γυνὴ ἣ ἐνταῦθα μένει.", "The woman who is staying here.")], kind="pronoun", section="pronouns"),
    A("hostis", "ὅστις, ἥτις, ὅ τι — whoever", "ὅστις", "pronoun", "ἥτις", "ὅ τι",
      "Indefinite relative and indirect interrogative. Both parts decline; Attic prose likes the short forms ὅτου, ὅτῳ.",
      [("ὅστις ἂν τοῦτο ποιῇ, δίκαιός ἐστιν.", "Whoever does this is just."), ("οὐκ οἶδα ὅ τι λέγεις.", "I do not know what you mean.")], kind="pronoun", section="pronouns"),
    A("tis-interrog", "τίς, τί — who? what?", "τίς", "pronoun", "τίς", "τί",
      "Always accented on the first syllable; the acute never changes to grave. τί also means ‘why?’.",
      [("τίς εἶ;", "Who are you?"), ("τί ποιεῖς;", "What are you doing?")], kind="pronoun", section="pronouns"),
    A("tis-indef", "τις, τι — someone, some", "τις", "pronoun", "τις", "τι",
      "The same forms without the accent (enclitic): ‘a certain’, ‘some’, ‘someone’.",
      [("ἀνήρ τις ἦλθεν.", "A man came."), ("λέγει τι.", "He is saying something.")], kind="pronoun", section="pronouns"),
    A("heautou", "ἑαυτοῦ — himself (reflexive)", "ἑαυτοῦ", "pronoun", "ἑαυτῆς", "ἑαυτοῦ",
      "Reflexives have no nominative. First person ἐμαυτοῦ, second σεαυτοῦ (σαυτοῦ), third ἑαυτοῦ (αὑτοῦ).",
      [("γνῶθι σεαυτόν.", "Know yourself."), ("ἑαυτὸν σῴζει.", "He saves himself.")], kind="pronoun", section="pronouns"),
    A("allelon", "ἀλλήλων — each other", "ἀλλήλων", "pronoun", "ἀλλήλων", "ἀλλήλων",
      "Plural (and dual) only, no nominative.",
      [("ἀλλήλους φιλοῦσιν.", "They love each other."), ("ἀλλήλοις βοηθοῦσιν.", "They help one another.")], kind="pronoun", section="pronouns"),
    A("oudeis", "οὐδείς, οὐδεμία, οὐδέν — no one, nothing", "οὐδείς", "pronoun", "οὐδεμία", "οὐδέν",
      "οὐδέ + εἷς. Use μηδείς where the negative would be μή.",
      [("οὐδεὶς ἀθάνατός ἐστιν.", "No one is immortal."), ("οὐδὲν λέγει.", "He says nothing.")], kind="pronoun", section="pronouns"),
    A("heis", "εἷς, μία, ἕν — one", "εἷς", "pronoun", "μία", "ἕν",
      "Masculine/neuter stem ἑν-, feminine μια-.",
      [("εἷς ἀνὴρ οὐδεὶς ἀνήρ.", "One man is no man."), ("μία πόλις.", "One city.")], kind="pronoun", section="pronouns"),
    A("dyo", "δύο — two", "δύο", "pronoun", "δύο", "δύο",
      "Dual endings; often left undeclined.",
      [("δύο ἵπποι.", "Two horses."), ("δυοῖν ἀδελφοῖν.", "Of two brothers.")], kind="pronoun", section="pronouns"),
    A("treis", "τρεῖς, τρία — three", "τρεῖς", "pronoun", "τρεῖς", "τρία",
      "Plural only; the neuter is τρία.",
      [("τρεῖς νῆες.", "Three ships."), ("τρία τέκνα.", "Three children.")], kind="pronoun", section="pronouns"),
    A("tettares", "τέτταρες, τέτταρα — four", "τέτταρες", "pronoun", "τέτταρες", "τέτταρα",
      "Attic τέτταρες (Koine τέσσαρες). Numbers from πέντε to ἑκατόν are indeclinable.",
      [("τέτταρες ἡμέραι.", "Four days."), ("τέτταρα ἔτη.", "Four years.")], kind="pronoun", section="pronouns"),

    V("luo", "λύω — the model -ω verb", "λύω",
      "Six principal parts (λύω, λύσω, ἔλυσα, λέλυκα, λέλυμαι, ἐλύθην) give six stems; every other form is stem + ending. The indicative of past tenses takes the augment ἐ-, the perfect reduplicates (λε-λυ-). Accent is recessive except where the tables show otherwise (λῦσαι, λελυκέναι, λυθείς).",
      [("οἱ πολέμιοι τοὺς αἰχμαλώτους λύουσιν.", "The enemy release the prisoners."), ("ἔλυσε τὸν ἵππον καὶ ἀπῆλθεν.", "He untied the horse and went away.")]),
    V("timao", "τιμάω — α-contract verbs", "τιμάω",
      "In the present and imperfect the stem vowel α contracts with the ending: α + ε/η → ᾱ, α + ο/ω/ου → ω, an ι in the ending survives as iota subscript (τιμᾷς). Elsewhere the α lengthens to η (τιμήσω, ἐτίμησα).",
      [("τοὺς θεοὺς τιμῶμεν.", "We honour the gods."), ("οἱ Ἀθηναῖοι τὸν Σωκράτη οὐκ ἐτίμων.", "The Athenians did not honour Socrates.")]),
    V("poieo", "ποιέω — ε-contract verbs", "ποιέω",
      "ε + ε → ει, ε + ο → ου; before a long vowel or diphthong the ε simply disappears (ποιῶ, ποιῇς). Other tenses lengthen ε to η (ποιήσω).",
      [("τί ποιεῖς;", "What are you doing?"), ("ὁ ποιητὴς καλὰ ποιήματα ἐποίει.", "The poet used to compose beautiful poems.")]),
    V("deloo", "δηλόω — ο-contract verbs", "δηλόω",
      "ο + ε/ο/ου → ου, ο + η/ω → ω, ο + any ι-diphthong → οι (δηλοῖς, δηλοῖ). Other tenses lengthen ο to ω (δηλώσω).",
      [("ὁ ἄγγελος τὰ γενόμενα δηλοῖ.", "The messenger reveals what happened."), ("ταῦτα ἐδήλου ἡ ἐπιστολή.", "The letter made this clear.")]),
    V("didomi", "δίδωμι — -μι verbs (ο-stem)", "δίδωμι",
      "The present reduplicates with ι (δι-δω-) and adds endings straight to the stem: long stem vowel in the singular (δίδωμι, δίδως, δίδωσι), short in the plural (δίδομεν). The aorist has κ in the singular only (ἔδωκα, ἔδωκας, ἔδωκε, but ἔδομεν, ἔδοτε, ἔδοσαν).",
      [("ὁ πατὴρ τῷ παιδὶ δῶρον δίδωσιν.", "The father gives his child a gift."), ("δός μοι τὸ ὕδωρ.", "Give me the water.")]),
    V("tithemi", "τίθημι — -μι verbs (ε-stem)", "τίθημι",
      "Like δίδωμι with ε/η: τίθημι, τίθης, τίθησι; τίθεμεν. Aorist ἔθηκα, ἔθεμεν; subjunctive θῶ; infinitive θεῖναι.",
      [("τὸν νόμον τίθησιν ὁ δῆμος.", "The people make the law."), ("ἔθηκε τὸ βιβλίον ἐπὶ τὴν τράπεζαν.", "He put the book on the table.")]),
    V("histemi", "ἵστημι — -μι verbs (α-stem)", "ἵστημι",
      "Present ἵστημι ‘I set up’; first aorist ἔστησα ‘I set up’ (transitive), root aorist ἔστην ‘I stood’ (intransitive); perfect ἕστηκα ‘I stand’. The subjunctive contracts with η/ω (ἱστῶ, ἱστῇς).",
      [("οἱ στρατιῶται τρόπαιον ἵστασαν.", "The soldiers were setting up a trophy."), ("ἔστη πρὸ τῆς θύρας.", "He stood in front of the door.")]),
    V("deiknymi", "δείκνυμι — -νυμι verbs", "δείκνυμι",
      "The suffix -νυ- appears only in the present and imperfect (δείκνῡμι, δείκνυμεν); all other tenses are regular from δεικ- (δείξω, ἔδειξα).",
      [("δείκνυσί μοι τὴν ὁδόν.", "He shows me the way."), ("δεῖξον ἡμῖν τὸ ἱερόν.", "Show us the temple.")]),
    V("eimi", "εἰμί — be", "εἰμί",
      "Irregular and mostly enclitic in the present. Learn the present, imperfect, future, subjunctive (ὦ), optative (εἴην), infinitive (εἶναι) and participle (ὤν, οὖσα, ὄν).",
      [("Σωκράτης σοφός ἐστιν.", "Socrates is wise."), ("ἦσαν ἐν τῇ ἀγορᾷ πολλοί.", "There were many people in the market-place.")]),
    V("eimi-go", "εἶμι — go (future ‘I shall go’)", "εἶμι",
      "In Attic prose the present indicative means ‘I shall go’ and serves as the future of ἔρχομαι; the other moods keep the present meaning (ἴθι ‘go!’, ἰέναι ‘to go’).",
      [("εἶμι εἰς τὴν πόλιν.", "I shall go to the city."), ("ἴθι δή, λέγε.", "Come now, speak.")]),
    V("phemi", "φημί — say", "φημί",
      "Enclitic present (except φῄς); imperfect ἔφην ‘I said’. οὔ φημι = ‘I say that … not, I deny’.",
      [("φησὶ ταῦτα ἀληθῆ εἶναι.", "He says this is true."), ("οὐκ ἔφη ἐλθεῖν.", "He said he had not come.")]),
    V("oida", "οἶδα — know", "οἶδα",
      "A perfect in form with present meaning; pluperfect ᾔδη = ‘I knew’. Infinitive εἰδέναι, participle εἰδώς.",
      [("οἶδα οὐδὲν εἰδώς.", "I know that I know nothing."), ("ᾔδει τὴν ὁδόν.", "He knew the way.")]),
    V("lambano", "λαμβάνω — second aorist", "λαμβάνω",
      "The second aorist uses a different stem (λαβ-) with the endings of the imperfect (ἔλαβον) and, outside the indicative, the endings of the present; but the infinitive, participle and (for a few verbs) the imperative 2 sg. are accented on the ending: λαβεῖν, λαβών, λαβέ.",
      [("ἔλαβε τὸ ἀργύριον.", "He took the money."), ("λαβὲ τὸ βιβλίον.", "Take the book.")]),
    V("phaino", "φαίνω — liquid stems", "φαίνω",
      "Stems in λ, μ, ν, ρ have no σ: the future is contract (φανῶ, φανεῖς) and the aorist lengthens the stem vowel instead (ἔφηνα). The aorist passive is second (ἐφάνην ‘I appeared’).",
      [("ὁ ἥλιος φαίνεται.", "The sun appears."), ("ἐφάνη ὁ φίλος ἐν τῇ ἀγορᾷ.", "The friend appeared in the market-place.")]),
    V("baino", "βαίνω — root aorist", "βαίνω",
      "The root aorist adds the endings directly to the long stem: ἔβην, ἔβης, ἔβη, ἔβημεν; subjunctive βῶ, infinitive βῆναι, participle βάς. So too ἔγνων (γιγνώσκω) and ἔστην (ἵστημι).",
      [("ἔβη εἰς τὴν ναῦν.", "He went aboard the ship."), ("ἔγνω τὴν ἀλήθειαν.", "He recognised the truth.")]),
    V("gignomai", "γίγνομαι — deponent verbs", "γίγνομαι",
      "Deponents have middle (or passive) forms with active meaning: γίγνομαι ‘I become’, ἐγενόμην ‘I became’. Some are passive deponents (ἐβουλήθην ‘I wished’).",
      [("τί ἐγένετο;", "What happened?"), ("νὺξ ἐγένετο.", "Night fell.")]),
]


@lru_cache(maxsize=1)
def _by_id() -> dict[str, dict]:
    return {p["id"]: p for p in PARADIGMS}


def index() -> dict:
    sections = []
    for sid, title, blurb in SECTIONS:
        items = [{"id": p["id"], "title": p["title"], "lemma": p["lemma"]} for p in PARADIGMS if p["section"] == sid]
        sections.append({"id": sid, "title": title, "blurb": blurb, "items": items})
    return {"sections": sections}


def table_for(paradigm: dict) -> dict | None:
    if paradigm["kind"] == "verb":
        from .verb import conjugate_entry  # local import: verbs come later

        return conjugate_entry(paradigm)
    return decline(paradigm["lemma"], paradigm["kind"], paradigm["subclass"], paradigm["morph"])


def get(paradigm_id: str) -> dict:
    p = _by_id()[paradigm_id]
    return {**p, "table": table_for(p)}
