"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import FormsTable from "../../../components/FormsTable";
import Highlight from "../../../components/Highlight";
import { SpeakButton, useSpeaker } from "../../../components/Speak";
import { getVocabEntry, type VocabEntry } from "../../../lib/api";

export default function WordPage() {
  const params = useParams<{ id: string }>();
  const id = decodeURIComponent(String(params?.id ?? ""));
  const [entry, setEntry] = useState<VocabEntry | null>(null);
  const [error, setError] = useState("");
  const { play, busy, error: playError } = useSpeaker();

  useEffect(() => {
    if (!id) return;
    getVocabEntry(id)
      .then(setEntry)
      .catch((e) => setError(e instanceof Error ? e.message : "Could not load the word"));
  }, [id]);

  if (error) return <main className="shell"><p className="error">{error}</p></main>;
  if (!entry) return <main className="shell"><p className="muted">Loading…</p></main>;

  return (
    <main className="shell">
      <p className="crumbs"><Link href="/vocab">← Vocab</Link></p>
      <section className="wordHeader">
        <div className="wordTitle">
          <h1 lang="grc">{entry.lemma}</h1>
          <SpeakButton text={entry.lemma} play={play} busy={busy} />
        </div>
        <p className="wordHeadword" lang="grc">{entry.headword}</p>
        <p className="wordMeta">
          <span className={`level ${entry.level}`}>{entry.level}</span> rank {entry.rank} · {entry.pos} · {entry.group}
          {entry.topics.length > 0 && <> · {entry.topics.join(", ")}</>}
        </p>
        <p className="wordDef">{entry.definition}</p>
        {entry.cognates?.derivatives && entry.cognates.derivatives.length > 0 && (
          <p className="cognateLine">From this word in English: <b>{entry.cognates.derivatives.join(", ")}</b></p>
        )}
        {entry.cognates?.cognates && entry.cognates.cognates.length > 0 && (
          <p className="cognateLine">Related by descent (same Indo-European root): <b>{entry.cognates.cognates.join(", ")}</b></p>
        )}
        {entry.notes && <p className="wordNote">{entry.notes}</p>}
        <p className="muted small">IPA (learner Attic): /{entry.ipa}/{playError && <> · {playError}</>}</p>
      </section>

      {entry.forms && (
        <section className="card">
          <h2>Forms</h2>
          <p className="muted small">Tap any form to hear it.</p>
          <FormsTable forms={entry.forms} play={play} />
        </section>
      )}

      {entry.examples.length > 0 && (
        <section className="card">
          <h2>In the readings</h2>
          <ul className="examples">
            {entry.examples.map((ex, i) => (
              <li key={i}>
                <p className="exampleText" lang="grc">
                  <Highlight text={ex.text} form={ex.form} /> <SpeakButton text={ex.text} play={play} busy={busy} small />
                </p>
                <p className="exampleMeta">
                  {ex.author}, <em>{ex.title}</em> ·{" "}
                  <Link href={`/?reading=${encodeURIComponent(ex.reading)}&sentence=${ex.sentence}`}>open in reader</Link>
                </p>
              </li>
            ))}
          </ul>
        </section>
      )}

      <p className="attribution">
        Entry from the <a href={entry.dcc_url} target="_blank" rel="noreferrer">DCC Greek Core Vocabulary</a> (CC BY-SA); forms generated by Attic Reader — report anything that looks wrong.
      </p>
    </main>
  );
}
